[workspace]
authors = [
    "Eric Codrea <ecodrea@anl.gov>" ,
    "Pete Jemian <prjemian+bits@gmail.com>",
    "Rafael Vescovi <rvescovi@anl.gov",
    ]

channels = ["conda-forge"]
name = "bits_instrument"
platforms = ["linux-64"]
version = "0.1.0"


[environments]
default = { solve-group = "default" }
all = { features = ["dev", "doc"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
doc = { features = ["doc"], solve-group = "default" }



[dependencies]
bluesky-base = "==1.14.4"
bluesky-queueserver = "*"
matplotlib-base= ">=3.9.3,<4"
networkx = ">=3.4.2,<4"
numpy = "*"
ophyd = "==1.11.0"
pyepics = "*"
python = ">=3.12,<3.13"
semver = ">=3.0.4,<4"
tiled-client = "==0.1.0b39"
colorlog = ">=6.9.0,<7"
pydantic-numpy = "*"
hdf5-external-filter-plugins = ">=0.1.0,<0.2"
blosc-hdf5-plugin = ">=1.0.1,<2"
databroker = "==1.2.5"
p4p = ">=4.2.0,<5"
epicscorelibs = ">=7.0.7.99.1.1,<8"
zarr = ">=3.1.2,<4"
suitcase-mongo = ">=0.7.0,<0.8"
suitcase-msgpack = ">=0.3.0,<0.4"
tqdm = ">=4.67.1,<5"
suitcase-jsonl = ">=0.2.2,<0.3"
apstools = ">=1.7.7,<2"
toml = ">=0.10.2,<0.11"
tomli = ">=2.2.1,<3"
tomli-w = ">=1.2.0,<2"
pyqt = "<6"
bluesky-queueserver-api = ">=0.0.12,<0.0.13"
jupyter = ">=1.1.1,<2"
bluesky-widgets = ">=0.0.17,<0.0.18"
qtpy = ">=2.4.3,<3"
tomlkit = ">=0.13.3,<0.14"
ipython = ">=9.5.0,<10"

[pypi-dependencies]
apsbits = ">=1.0.5, <2"
ophyd-async = { version = ">0.10.0", extras = ["ca", "pva"] }
11bm-bits = { path = ".", editable = true }

[feature.dev.dependencies]
isort = "*"
mypy = "*"
pre-commit = "*"
pytest = "*"
ruff = "*"

[feature.doc.dependencies]
babel = "*"
ipykernel = "*"
jinja2 = "*"
markupsafe = "*"
nbsphinx = "*"
pydata-sphinx-theme = "*"
pygments = "*"
sphinx-design = "*"
sphinx-tabs = "*"
sphinx = "*"
myst-parser = ">=4.0.1,<5"

[tasks]
qs_restart = "src/bm11_b_qserver/qs_host.sh restart"
qs_host = "src/bm11_b_qserver/qs_host.sh"
qs_start_manager = { cmd = "start-re-manager --config=./qs-confdig.yml", cwd = "qserver" }
start = { cmd = "ipython -i -c 'from bm11_b.startup import *'", env = { MPLBACKEND = "qt5agg" } }